# application.properties
recaptcha.site.key=6LeEYooqAAAAAH2ogyEfXXzUkqvS0VH0VTwQkGjh
recaptcha.secret.key=6LeEYooqAAAAAOggttPuqtDJxI-yFaW0-eQ2RN1P

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kimxx54@gmail.com
spring.mail.password=kmrw mesd azuf dnwj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true